version: '3'

services:
  db:
    container_name: bulletin-db
    image: postgres
    hostname: db
    environment: 
      GET_HOST_FROM: dns
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: mysecretpassword
    ports: 
      - 5432:5432
    networks: 
      - bulletin_net
  bulletin-api:
    container_name: bulletin-api
    image: petersonsalme/bulletin-api:v1
    hostname: bulletin-api
    build: 
      context: .
      dockerfile: docker/Dockerfile
    environment: 
      GET_HOST_FROM: dns
    networks: 
      - bulletin_net
    depends_on: 
      - db
    links:
      - db
    ports: 
      - 8080:8080
    labels: 
      kompose.service.type: LoadBalancer
networks: 
  bulletin_net:
    driver: bridge